apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api-gateway
  template:
    metadata:
      labels:
        app: k8s-api-gateway
    spec:
      containers:
        - name: k8s-api-gateway
          image: eomtaebeom/k8s-api-gateway:0.0.6
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prd
          ports:
            - containerPort: 8080
          args:
            - "--spring.config.import=optional:file:/etc/config/application-dev.yml"
          volumeMounts:
            - name: api-gateway-config-volume
              mountPath: /etc/config/application-dev.yml
              subPath: application-dev.yml
            - name: api-gateway-secret-volume
              mountPath: /etc/secret

      volumes:
        - name: api-gateway-config-volume
          configMap:
            name: api-gateway-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: api-gateway-secret-volume
          secret:
            secretName: api-gateway-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml
